# This is a basic workflow to help you get started with Actions

name: CI - Testes com Capybara

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Capybara@${{ matrix.browser}} ${{ matrix.os }} headless=${{ matrix.headless }}
    strategy:
      fail-fast: false
      matrix:
        browser: [ chrome, firefox, opera ]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      # instalar a lib que vai criar o report do allure
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install operating system dependencies
        run: npm install -g allure-commandline --save-dev
      - name: Install Opera
        if: always()
        continue-on-error: true
      - run:  brew install caskroom/cask/brew-cask 2> /dev/null |
              brew install --cask opera
      - run: chmod +x ./webdrivers/**
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        # uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
      - run: |
          gem install cucumber
          gem install httparty
          bundler install
          bundle exec cucumber
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: logs
          destination_dir: ${{ matrix.browser}}