name: Test com Capybara e Selenium

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 5"

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]
        browser: [ chrome, firefox, safari ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-firefox@latest
      - run: firefox --version
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install operating system dependencies
        run: npm install -g allure-commandline --save-dev
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        # uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run tests
        run: |
             gem install cucumber
             bundle exec cucumber BROWSER=${{matrix.browser}}

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./report
          destination_dir: ${{ matrix.browser}}
